// Notas de versión. Añadir las nuevas entradas al principio de la lista.
export const releaseNotes = [
    {
        id: "2026-10-08-community-patch", date: "2026-10-08", category: "Parche y mejoras", icon: "update",
        title: "Mejoras solicitadas por usuarios: tareas, imágenes y equipo conectado",
        summary: "Cambios del 8 de octubre: sugerencias, miembros conectados, imágenes en Drive, carpetas compartidas de Workspace y correcciones para trabajar con menos interrupciones.",
        sections: [
            {title: "Sugerencias y reportes de usuarios", items: [
                "Envía problemas, ideas y mejoras visuales con título, descripción, módulo, prioridad y datos del navegador o dispositivo.",
                "Consulta tus reportes y su estado. El equipo autorizado puede revisar, priorizar y registrar el seguimiento interno.",
                "Las imágenes se agregan directamente en la descripción. Se retiró el apartado separado de Capturas; las capturas anteriores siguen disponibles dentro de la descripción.",
                "Se corrigió el visor de imágenes para que aparezca delante del detalle del reporte.",
            ]},
            {title: "Miembros conectados y personas del proyecto", items: [
                "El botón de miembros de la barra superior abre un panel lateral animado con las personas conectadas, agrupadas por departamento y con su cantidad.",
                "Consulta la foto de perfil, el nombre y el estado de cada persona. Busca por persona o estado desde el panel.",
                "El panel de miembros reemplaza el widget de equipo conectado. Se ajustaron su ancho, distribución y animaciones de apertura y cierre.",
                "Al pulsar los avatares de un proyecto se abre una ventana pequeña animada con sus miembros. Busca por nombre o correo y agrega personas desde los resultados.",
                "La lista de personas del proyecto permite quitar miembros y desplazarse cuando hay varias personas. Se ajustó el tamaño del botón de eliminar.",
            ]},
            {title: "Carpetas y accesos de Workspace", items: [
                "Agrega carpetas de Drive desde la misma ventana donde seleccionas proyectos y tareas. El selector permite buscar, navegar y crear carpetas.",
                "Los accesos a carpetas de Drive se abren dentro del módulo Drive de BOLD. Quitar un acceso del Workspace conserva la carpeta original.",
                "Comparte las carpetas que creaste con personas de tu departamento. Busca por nombre o correo para agregarlas y usa el botón de eliminar para quitar su acceso.",
                "Las personas seleccionadas ven la carpeta compartida y sus subcarpetas en modo consulta. El creador controla su organización y los cambios se actualizan en segundo plano.",
                "Compartir una carpeta de Workspace mantiene los permisos existentes de proyectos, tareas y Google Drive.",
                "Se ajustaron los botones de eliminar para que sean compactos. Las descripciones de carpetas y la creación de proyectos ya no ofrecen adjuntar imágenes.",
            ]},
            {title: "Tareas, subtareas y comentarios", items: [
                "Las tareas y los comentarios con imágenes aparecen inmediatamente para quien los envía mientras el guardado y la sincronización continúan en segundo plano.",
                "Los comentarios nuevos permanecen abajo durante la sincronización y después de guardarse. El aviso de sincronización se muestra arriba a la derecha, sin repetirlo dentro de cada comentario.",
                "En comentarios, Enter envía y Shift + Enter agrega un nuevo renglón.",
                "Cada subtarea tiene un botón de eliminar. Al pulsar el resto de su fila se abren sus detalles, conservando las acciones del nombre y la casilla de completado.",
                "El cronograma muestra únicamente los comentarios enviados desde cronograma; ya no mezcla los comentarios de las tareas.",
                "Los paneles de crear, consultar y editar tareas y proyectos usan un ancho inicial de 600 px, con tamaño ajustable dentro de sus límites.",
            ]},
            {title: "Imágenes, carrusel y zoom", items: [
                "Las imágenes de las descripciones se muestran como miniaturas pequeñas, alineadas a la izquierda y con bordes redondeados.",
                "Pulsa una miniatura para ampliar la imagen y recorrer el carrusel. El visor conserva las proporciones de imágenes horizontales y verticales.",
                "Amplía hasta el 400 % con los botones o la rueda del mouse. Arrastra la imagen ampliada y restablece el zoom al 100 % cuando lo necesites.",
                "Los comentarios disponen de carrusel para consultar sus imágenes. El carrusel del cronograma respeta la separación de sus comentarios.",
                "Se corrigieron fotos de perfil que aparecían demasiado grandes en tareas y proyectos, y problemas de superposición del visor con otras ventanas.",
            ]},
            {title: "Almacenamiento de imágenes en Drive", items: [
                "Administración → Conectores permite seleccionar la carpeta de Drive donde BOLD guarda las imágenes mediante la cuenta administradora conectada.",
                "Las imágenes se organizan en subcarpetas por módulo, proyecto, tarea y usuario, separando descripción, comentarios y cronograma.",
                "El selector de destino permite crear carpetas desde Administración y Docs.",
                "La conexión personal de cada usuario al módulo Drive se mantiene independiente del almacenamiento de imágenes de BOLD.",
                "Se ajustó el guardado de tareas con imágenes para evitar esperas que bloqueaban otras acciones. Los errores de guardado conservan un borrador recuperable.",
            ]},
            {title: "Archivos y vistas previas de Drive", items: [
                "Descarga carpetas como archivos ZIP desde Drive en BOLD.",
                "Las tarjetas de archivos muestran vistas previas cuando Drive las proporciona, con un icono de respaldo cuando no están disponibles.",
                "Las miniaturas se conservan en el navegador por cuenta y versión del archivo para reutilizarlas y cargar las nuevas o modificadas.",
                "Se retiraron límites adicionales de BOLD para las cargas y descargas; siguen aplicándose los límites de Google y del entorno donde se utiliza la aplicación.",
            ]},
            {title: "Avisos y acceso a Novedades", items: [
                "Novedades tiene un botón junto a Ayuda y una animación cuando hay una publicación nueva por consultar.",
                "Si entras con notificaciones pendientes, BOLD reproduce el sonido una vez en Inicio, después de la animación de entrada y según tus preferencias de sonido.",
                "Los avisos de guardado, sincronización y confirmación utilizan los tres puntos animados de BOLD en rojo, adaptados a su tamaño y con un ciclo más rápido.",
                "Los avisos flotantes se muestran sobre los paneles y carruseles para mantenerlos visibles durante el trabajo.",
                "Los avisos de tareas cuyo guardado no pudo confirmarse incluyen Cerrar y No volver a mostrar. Esta última opción silencia el aviso de esa tarea en el navegador sin borrar su borrador.",
                "Se restauró el acceso a Ayuda y se ajustaron los botones superiores. La campana conserva su animación y añade el contorno del modo oscuro.",
                "La campana repite su animación mientras hay notificaciones sin leer y muestra el mismo punto rojo que Novedades, también en móvil.",
            ]},
            {title: "Correcciones del editor y presentación", items: [
                "Se ajustó el cambio de estilo de texto para conservar el renglón y la selección al editar descripciones.",
                "Se mejoraron la alineación de avatares, las miniaturas y los paneles para mantener una presentación consistente entre módulos.",
                "Las nuevas animaciones respetan la preferencia de movimiento reducido del dispositivo.",
            ]},
        ],
    },
    {
        id: "2026-10-05-major-update", date: "2026-10-05", category: "Actualización general", icon: "update",
        title: "Gran actualización de BOLD: Drive, Docs, Calendario y Perfil",
        summary: "Una demo más completa: archivos, editores, conexión Google, personalización y mejoras en el trabajo diario.",
        sections: [
            {title: "Drive dentro de BOLD", items: [
                "Navega por Página principal, Mi unidad, Unidades compartidas, Compartido conmigo, Reciente, Destacados, Papelera y Almacenamiento.",
                "Usa las vistas de lista y cuadrícula, búsqueda, filtros, ordenamiento, selección múltiple, menús de archivo y panel de detalles.",
                "Crea carpetas, sube archivos o carpetas y arrastra archivos para iniciar una carga. Elige su destino para mantener organizada tu unidad.",
                "Renombra, destaca, copia, mueve y comparte archivos según los permisos de tu cuenta. Consulta imágenes y PDF desde la vista previa.",
                "Las vistas visitadas conservan sus datos mientras se actualizan en segundo plano. Se corrigieron descargas, menús fuera de pantalla y la transición al regresar a una carpeta.",
            ]},
            {title: "Docs, hojas de cálculo y presentaciones", items: [
                "Crea documentos, hojas de cálculo y presentaciones desde Docs. Antes de crearlos, selecciona el nombre y la carpeta de Drive donde se guardarán.",
                "Abre archivos compatibles desde Drive en los editores de BOLD, con herramientas de lectura y edición para cada formato.",
                "La edición de archivos Office conserva el archivo original cuando el formato es compatible. Los formatos antiguos pueden requerir una conversión inicial, que se reutiliza en aperturas posteriores.",
                "Mantén la opción Abrir en Google para usar el editor completo de Google y sus herramientas adicionales.",
                "La portada de Docs se simplificó para mostrar los tres tipos de archivo; la biblioteca completa se consulta en Drive.",
            ]},
            {title: "Calendario y búsqueda de invitados", items: [
                "Calendario utiliza la cuenta Google individual del usuario y conserva las vistas visitadas mientras actualiza sus datos en segundo plano.",
                "Las sugerencias de invitados combinan contactos de Google People y direcciones disponibles en Gmail. También puedes escribir un correo completo para invitar a alguien nuevo.",
                "Se mejoró el manejo de búsquedas lentas y respuestas antiguas para evitar sugerencias incorrectas al cambiar lo que escribes.",
                "Se corrigió la edición de recurrencia para permitir volver a No se repite después de configurar un evento recurrente.",
            ]},
            {title: "Conexión Google unificada", items: [
                "Conecta Drive, Docs, Sheets, Slides, Calendario, Tasks, Contactos y Gmail desde una sola conexión, autorizando sus permisos en Google.",
                "Administración → Conectores concentra la configuración de Google Cloud. Cada empleado conecta su propia cuenta desde sus preferencias.",
                "Drive y Docs muestran el correo conectado. Los accesos laterales de Drive llevan a Tareas y Calendario de BOLD.",
            ]},
            {title: "Perfil, personalización y atajos", items: [
                "El perfil reúne Cuenta, Conectores, Notificaciones, Atajos y Novedades.",
                "Edita tu nombre sobre la tarjeta, sube y recorta tu foto y selecciona el color del banner. El selector de colores también se utiliza en Proyectos y Workspaces.",
                "Cambia de departamento desde la ficha rápida sin cerrar sesión. El selector aparece en un panel lateral y Novedades tiene acceso directo desde esa ficha.",
                "Personaliza los atajos de navegación, búsqueda, notificaciones y tema. Puedes desactivarlos, restaurarlos y guardarlos para tu cuenta.",
            ]},
            {title: "Notificaciones y tareas", items: [
                "Elige entre cinco sonidos de notificación, ajusta el volumen o sube un sonido personalizado. Puedes solicitar avisos de Windows mientras BOLD esté abierto.",
                "La campana se anima al recibir un aviso y al abrir las notificaciones. El panel permite limpiar los avisos del departamento activo.",
                "Las tareas completadas se muestran al final de su sección. El movimiento entre secciones responde inmediatamente y confirma el cambio con el servidor.",
                "El bloc de notas privado permite guardar tus notas y consultarlas desde otro dispositivo con tu cuenta.",
            ]},
            {title: "Diseño y navegación", items: [
                "Se añadieron respuestas visuales a botones, widgets, perfil y ajustes, respetando los modos claro y oscuro y el movimiento reducido.",
                "Las confirmaciones de la aplicación utilizan ventanas con el diseño de BOLD. Las notas de parche mantienen visible la página que hay detrás.",
                "Los botones Atrás y Adelante del navegador, incluidos los laterales del mouse, permiten regresar entre módulos y vistas.",
                "Se corrigieron accesos a Proyectos y Workspaces y problemas con sus selectores de color.",
            ]},
        ],
    },
    {
        id: "2026-10-05-shortcuts", date: "2026-10-05", category: "Nueva función", icon: "keyboard",
        title: "Tus atajos, a tu manera",
        summary: "Navega entre módulos y personaliza tus combinaciones desde Perfil → Atajos.",
        sections: [
            {title: "Atajos de teclado", items: ["Accede a Inicio, Tareas, Proyectos, Workspaces, Calendario, Drive y Docs mediante el teclado.", "Abre la búsqueda y las notificaciones, o cambia el tema con una combinación.", "Consulta la lista completa en Perfil → Atajos. También encontrarás las teclas de edición y navegación que ya funcionan en BOLD."]},
            {title: "Preferencias personales", items: ["Cambia una combinación presionando las teclas que quieres usar. Puedes desactivar atajos o restaurar los valores predeterminados.", "Guarda los cambios para aplicarlos a tu cuenta. Las preferencias se conservan entre dispositivos.", "BOLD detecta combinaciones duplicadas y reservadas. Los atajos de navegación respetan tus permisos y no se ejecutan mientras escribes o hay un diálogo abierto."]},
        ],
    },
    {
        id: "2026-10-05-notifications", date: "2026-10-05", category: "Mejoras", icon: "bell",
        title: "Notificaciones con más personalidad",
        summary: "Sonidos personalizados, avisos de Windows y una campana que responde a cada novedad.",
        sections: [
            {title: "Sonidos y avisos", items: ["Elige entre cinco sonidos o sube tu propio audio desde Perfil → Notificaciones. Puedes ajustar el volumen y escuchar una muestra.", "Solicita el permiso del navegador para recibir avisos de Windows mientras BOLD está abierto.", "Limpia las notificaciones de tu departamento activo desde el panel o las preferencias, sin borrar tareas ni eventos."]},
            {title: "Respuesta visual", items: ["La campana se mueve al llegar una notificación nueva y al abrir el panel, con la animación rápida de 520 ms.", "BOLD comprueba los avisos cada dos segundos mientras la aplicación está visible.", "Las animaciones respetan la preferencia de movimiento reducido del dispositivo."]},
        ],
    },
    {
        id: "2026-10-05-profile", date: "2026-10-05", category: "Experiencia BOLD", icon: "profile",
        title: "Un perfil más fácil de personalizar",
        summary: "Edita tu tarjeta, ajusta tu foto y encuentra tus preferencias en un solo lugar.",
        sections: [
            {title: "Tu tarjeta de perfil", items: ["Edita el nombre directamente en tu tarjeta y selecciona una foto de perfil.", "Ajusta el tamaño y el recorte de tu imagen antes de aplicarla. Cambia el color del banner con el selector compartido de BOLD.", "Los accesos al perfil y el botón de ajustes responden al pasar el mouse, con estilos para los temas claro y oscuro."]},
            {title: "Preferencias y novedades", items: ["Cuenta, Conectores, Notificaciones y Atajos están disponibles desde Perfil.", "Las confirmaciones dentro de la aplicación usan ventanas con el diseño de BOLD.", "El nuevo apartado Novedades reúne las notas de la demo. Abre una tarjeta para consultar sus cambios completos."]},
        ],
    },
];
