// The short tour mirrors the current Bold layouts; all names and counts are fictional.
const scenes = [...document.querySelectorAll('.scene')];
const set = (index, selector, html) => { const target = scenes[index].querySelector(selector); if (target) target.innerHTML = html; };
const taskNav = '<div class="tabs"><strong>Tareas</strong><span>Cronograma</span><small class="tab-tools">Ordenar &nbsp; Filtrar &nbsp; Personalizar</small></div>';
const sidebar = '<b>bold<span>.</span></b><div>⌂ &nbsp; Inicio</div><div>✓ &nbsp; Tareas</div><div>▣ &nbsp; Bandeja de entrada</div><div>▦ &nbsp; Calendario</div><div>▤ &nbsp; Informes</div>';
scenes.slice(1, 7).forEach((scene, index) => {
  const aside = scene.querySelector('aside');
  aside.innerHTML = sidebar;
  aside.querySelectorAll('div')[index === 2 ? 1 : index === 3 ? 2 : index === 4 ? 3 : index === 5 ? 4 : index].classList.add('active');
});
set(0, '.login-form', `<small>BOLD</small><h2>Bienvenido de nuevo</h2><p>Ingresa a tu cuenta para continuar.</p><label>Correo electrónico<div class="field">demo@ejemplo.com</div></label><label>Contraseña<div class="field">•••••••••••• <span class="eye">◉</span></div></label><div class="login-options"><span>□ &nbsp; Recordar correo</span><b>¿Olvidaste tu contraseña?</b></div><button class="action primary">Iniciar sesión</button><div class="reveal login-next"><small>BOLD</small><h2>Selecciona tu cargo</h2><p>Elige la asignación con la que quieres continuar.</p><label>Cargo activo<div class="field">Coordinación · Equipo de proyectos &nbsp;⌄</div></label></div>`);
set(1, '.app main', `<header><h2>Buenos días</h2><small>Esto es lo más importante para hoy</small></header><div class="home-grid"><article class="widget"><h3>◉ &nbsp; Tareas por estado <span>⋮</span></h3><div class="status-rings"><div><b>3</b><small>Pendientes</small></div><div><b>2</b><small>En curso</small></div><div><b>4</b><small>Completadas</small></div></div></article><article class="widget"><h3>▣ &nbsp; Proyectos <span>⋮</span></h3><p>Lanzamiento Aurora</p><div class="progress"><div style="width:33%"></div></div><small>1 de 3 tareas completadas</small></article><article class="widget wide"><h3>✓ &nbsp; Mis tareas <span>⋮</span></h3><nav>Hoy &nbsp;&nbsp; Próximas &nbsp;&nbsp; Sin fecha</nav><button class="home-task action">○ &nbsp; Preparar presentación <em>Alta · Hoy</em></button><div class="home-task">○ &nbsp; Revisar propuesta <em>Media · Mañana</em></div><footer>+ Agregar tarea rápida</footer></article><article class="widget"><h3>▦ &nbsp; Próximos vencimientos <span>⋮</span></h3><p>Preparar presentación</p><small>05 oct 2026</small></article></div><div class="reveal detail-drawer"><small>DETALLE DE TAREA</small><h3>Preparar presentación</h3><p>Prioridad: Alta</p><p>Proyecto: Lanzamiento Aurora</p><p>Fecha límite: 05 oct 2026</p></div>`);
set(2, '.app main', `<header class="with-button"><div><h2>Mis tareas</h2><small>Tareas asignadas a ti</small></div><button class="primary action">＋ Agregar tarea</button></header>${taskNav}<div class="table"><div class="table-head">TAREA <span>RESPONSABLE</span><span>FECHA</span><span>PRIORIDAD</span></div><div class="section-head">⌄ &nbsp; MIS TAREAS &nbsp; 3</div><div class="task-row">□ &nbsp; Revisar propuesta <em>03 oct 2026</em><i>MEDIA</i></div><div class="task-row">□ &nbsp; Preparar presentación <em>05 oct 2026</em><i>ALTA</i></div><div class="reveal more task-row">□ &nbsp; Enviar propuesta <em>06 oct 2026</em><i>ALTA</i></div><div class="task-footer">+ Agregar tarea<br>+ Nueva sección</div><div class="task-progress">3 tareas · 1 completada <div class="progress"><div style="width:33%"></div></div></div></div><div class="reveal hide-after editor"><h3>Nueva tarea</h3><label>Nombre de la tarea<div class="field">Enviar propuesta</div></label><div class="editor-cols"><label>Fecha límite<div class="field">06 oct 2026</div></label><label>Prioridad<div class="field">Alta</div></label></div><button class="primary">Guardar</button></div>`);
set(3, '.app main', `<header><h2>Lanzamiento Aurora</h2><small>Proyecto · Equipo de proyectos</small></header>${taskNav}<div class="table"><div class="table-head">TAREA <span>FECHA</span><span>PRIORIDAD</span></div><div class="section-head">⌄ &nbsp; SIN SECCIÓN &nbsp; 3</div><div class="task-row">☑ &nbsp; Definir objetivos <em>01 oct</em><i>MEDIA</i></div><div class="task-row"><button class="project-check action">□</button> &nbsp; Preparar presentación <em>05 oct</em><i>ALTA</i></div><div class="task-row">□ &nbsp; Enviar propuesta <em>06 oct</em><i>ALTA</i></div><div class="task-footer">+ Agregar tarea</div><div class="project-total">3 tareas · <span class="before">1 completada</span><span class="reveal after">2 completadas</span><div class="progress"><div class="before" style="width:33%"></div><div class="reveal after" style="width:67%"></div></div><b class="before">33%</b><b class="reveal after">67%</b></div></div>`);
set(4, '.app main', `<header class="with-button"><div><h2>Bandeja de entrada</h2><small>Mantente al día con la actividad de tus tareas y proyectos</small></div><span class="unread">2 sin leer</span></header><div class="tabs"><strong>Todas</strong><span>Sin leer</span><span>Guardadas</span></div><div class="inbox-tools">⌕ &nbsp; Buscar en actividad... <span>Filtrar &nbsp; Más recientes</span></div><div class="inbox"><div><h4>HOY</h4><button class="inbox-row action"><i>AM</i><span><b>Nuevo comentario en Preparar presentación</b><small>Alex Moreno · Comentario · Revisa el diseño final</small></span><time>09:30</time></button><div class="inbox-row"><i>LP</i><span><b>Fecha actualizada en Revisar propuesta</b><small>Laura Pérez · Tarea</small></span><time>08:45</time></div></div><div class="reveal inbox-detail"><small>DETALLE</small><h3>Preparar presentación</h3><p>Revisa el diseño final</p><p>Proyecto: Lanzamiento Aurora</p><button class="primary">Abrir tarea ↗</button></div></div>`);
set(5, '.app main', `<header><h2>Calendario</h2><small>Calendario conectado · America/Tegucigalpa</small></header><div class="calendar-layout"><div class="calendar-side"><button class="calendar-create action">＋ &nbsp; Crear &nbsp;⌄</button><div class="mini-month">octubre 2026<div>Do &nbsp; Lu &nbsp; Ma &nbsp; Mi &nbsp; Ju &nbsp; Vi &nbsp; Sá</div><p>4 &nbsp; 5 &nbsp; 6 &nbsp; 7 &nbsp; 8 &nbsp; 9 &nbsp; 10</p></div><small>Mis calendarios</small><p>☑ &nbsp; Principal</p></div><div class="calendar-main"><div class="calendar-tools"><b>Hoy &nbsp; ‹ &nbsp; › &nbsp; octubre 2026</b><span>Día &nbsp; <strong>Semana</strong> &nbsp; Mes &nbsp; Agenda</span></div><div class="week-head">LUN 05 &nbsp;&nbsp;&nbsp; MAR 06 &nbsp;&nbsp;&nbsp; MIÉ 07 &nbsp;&nbsp;&nbsp; JUE 08 &nbsp;&nbsp;&nbsp; VIE 09</div><div class="week-grid"><div>9 a. m.</div><div>10 a. m.</div><div>11 a. m.</div><div class="reveal more event">Reunión con cliente<br><small>9:00–10:00 a. m.</small></div></div></div></div><div class="reveal hide-after event-editor"><h3>Evento nuevo</h3><div class="field">Reunión con cliente</div><div class="field">05 oct 2026 &nbsp; 9:00–10:00 a. m.</div><div class="field">cliente@ejemplo.com</div><button class="primary">Guardar</button></div>`);
set(6, '.app main', `<header class="with-button"><div><h2>Informes</h2><small>Resumen del rendimiento de BOLD Workspace</small></div><div class="report-actions"><span>Últimos 30 días &nbsp;⌄</span><button class="primary action">＋ Crear informe</button></div></header><p class="report-scope">Tareas con vencimiento en el período seleccionado.</p><div class="report-metrics"><article><small>TAREAS TOTALES</small><b>12</b></article><article><small>COMPLETADAS</small><b>5</b></article><article><small>EN CURSO</small><b>3</b></article><article><small>RETRASADAS</small><b>1</b></article></div><div class="report-charts"><article><h3>Tareas completadas por semana</h3><div class="bars"><span style="height:35%"></span><span style="height:58%"></span><span style="height:42%"></span><span style="height:82%"></span><span style="height:70%"></span></div></article><article><h3>Estado del trabajo</h3><div class="donut"><b>42%</b></div></article></div><div class="reveal report-toast">✓ Informe CSV descargado.</div>`);
scenes[0].querySelector('.copy p').textContent = 'Inicia sesión y selecciona el cargo con el que trabajarás.';
scenes[1].querySelector('.copy p').textContent = 'Los widgets reúnen tareas, proyectos y vencimientos. Abre una tarea para ver sus detalles.';
scenes[2].querySelector('.copy p').textContent = 'Indica el título, la fecha y la prioridad. La tarea aparecerá en la lista del proyecto.';
scenes[3].querySelector('.copy p').textContent = 'Al completar una tarea, el progreso del proyecto refleja el cambio.';
scenes[4].querySelector('.copy p').textContent = 'Abre una notificación y consulta la tarea relacionada desde la bandeja.';
scenes[5].querySelector('.copy p').textContent = 'Desde el calendario crea un evento con hora e invita por correo.';
scenes[6].querySelector('.copy p').textContent = 'Consulta las métricas del período y descarga un informe CSV.';
scenes[1].querySelector('.detail-drawer').setAttribute('data-layout-allow-overlap', '');
scenes[5].querySelector('.event-editor').setAttribute('data-layout-allow-overlap', '');
scenes[2].querySelector('.section-head').textContent = '⌄   MIS TAREAS';
scenes[2].querySelector('.task-progress').innerHTML = '<span class="before">2 tareas · 0 completadas</span><span class="reveal more">3 tareas · 0 completadas</span><div class="progress"><div style="width:0%"></div></div>';
scenes[5].querySelector('.calendar-create').classList.remove('action');
scenes[5].querySelector('.week-grid').insertAdjacentHTML('beforeend', '<button class="calendar-slot action" aria-label="Crear evento el 5 de octubre a las 9">＋</button>');
scenes[5].querySelector('.calendar-slot').classList.add('hide-after');
scenes[1].querySelector('.home-task:not(.action) em').textContent = 'Media · 07 oct';
scenes[1].querySelector('.widget:nth-child(2) .progress > div').style.width = '50%';
scenes[1].querySelector('.widget:nth-child(2) small').textContent = '1 de 2 tareas completadas';
scenes[2].querySelector('.editor-cols').insertAdjacentHTML('afterend', '<label>Proyecto<div class="field">Lanzamiento Aurora</div></label>');
scenes[2].querySelector('.task-row:not(.reveal) em').textContent = '07 oct 2026';
const taskScene = scenes[2];
taskScene.querySelector('.copy p').textContent = 'Crea una tarea en su proyecto y alterna entre la lista y la vista en columnas.';
taskScene.querySelector('.tabs').insertAdjacentHTML('beforeend', `<div class="tour-view-switch" role="group" aria-label="Cambiar estilo de visualización"><button class="tour-list is-active" title="Vista en lista" aria-label="Vista en lista"><svg viewBox="0 0 26 20" fill="currentColor"><circle cx="3" cy="3.5" r="2.5"/><rect x="8.5" y="1.5" width="16.5" height="4" rx="2"/><circle cx="3" cy="10" r="2.5"/><rect x="8.5" y="8" width="16.5" height="4" rx="2"/><circle cx="3" cy="16.5" r="2.5"/><rect x="8.5" y="14.5" width="16.5" height="4" rx="2"/></svg></button><button class="tour-columns" title="Vista en columnas" aria-label="Vista en columnas"><svg viewBox="0 0 24 22" fill="none" stroke="currentColor" stroke-width="2.2"><rect x="1.5" y="1.5" width="5" height="19" rx="2"/><rect x="9.5" y="1.5" width="5" height="19" rx="2"/><rect x="17.5" y="1.5" width="5" height="19" rx="2"/></svg></button></div>`);
taskScene.querySelector('.editor').innerHTML = `<header><div><small>NUEVA TAREA</small><h3>Crear nueva tarea</h3></div><span>×</span></header><div class="tour-editor-fields"><label>Nombre de la tarea *<div class="field">Enviar propuesta</div></label><div class="editor-cols"><label>Proyecto<div class="field">Lanzamiento Aurora ⌄</div></label><label>Sección<div class="field">Sin sección ⌄</div></label></div><label>Fecha límite<div class="field">▦ &nbsp; 06 oct 2026</div></label><div class="editor-cols"><label>Equipo responsable<div class="field">Equipo de proyectos ⌄</div></label><label>Responsable<div class="field">Sin responsable ⌄</div></label></div><label>Colaboradores asignados (0)<div class="field muted">Selecciona personas para seguir esta tarea</div></label><label>Prioridad<div class="field">🟠 &nbsp; Alta ⌄</div></label><label>Descripción<div class="field description">Añade una descripción...</div></label><p>＋ Agregar subtarea</p><label>Archivos adjuntos<div class="field muted">♧ &nbsp; Agregar archivos adjuntos</div></label></div><footer><button>Cancelar</button><button class="primary">Crear tarea</button></footer>`;
taskScene.querySelector('.app main').insertAdjacentHTML('beforeend', `<div class="reveal tour-board"><section><header>SIN SECCIÓN <span>3</span></header><article><strong>Revisar propuesta</strong><small>Media · 07 oct</small></article><article><strong>Preparar presentación</strong><small>Alta · 05 oct</small></article><article><strong>Enviar propuesta</strong><small>Alta · 06 oct</small></article><button>+ Agregar tarea</button></section><section class="tour-add-section">+ Nueva sección</section></div>`);
scenes[1].querySelector('.home-grid').setAttribute('data-layout-allow-overlap', '');
scenes[5].querySelector('.calendar-tools').setAttribute('data-layout-allow-overlap', '');
scenes[5].querySelector('.calendar-slot').setAttribute('data-layout-allow-overlap', '');

// The extra beats in this revision follow the real light-mode screens.
scenes[0].querySelector('.login-next .field').innerHTML = '<span class="role-choice">Selecciona un cargo</span><span>⌄</span>';
scenes[0].querySelector('.login-next label').insertAdjacentHTML('beforeend', '<div class="role-menu reveal"><div class="role-option">Marketing · Equipo de marketing</div><div>Coordinación · Equipo de proyectos</div></div>');
scenes[1].querySelector('.app main').innerHTML = `<header class="with-button"><div><h2>Buenos días</h2><small>Esto es lo más importante para hoy</small></div><button class="primary add-widget">＋ Agregar widget</button></header><div class="home-grid"><article class="widget"><h3>◉ &nbsp; Tareas por estado <span>⋮</span></h3><div class="status-rings"><div><b>1</b><small>Completadas</small></div><div><b>0</b><small>En curso</small></div><div><b>5</b><small>Pendientes</small></div></div></article><article class="widget"><h3>▣ &nbsp; Proyectos <span>⋮</span></h3><p>Lanzamiento Aurora</p><div class="progress"><div style="width:50%"></div></div><small>1 de 2 tareas completadas</small></article><article class="widget"><h3>✓ &nbsp; Mis tareas <span>⋮</span></h3><nav>Hoy &nbsp;&nbsp; Próximas &nbsp;&nbsp; Sin fecha</nav><button class="home-task action">◯ &nbsp; Nueva tarea <em>Media · Hoy</em></button><div class="home-task">◯ &nbsp; Revisar propuesta <em>Media · 07 oct</em></div><footer>+ Agregar tarea rápida</footer></article><article class="widget"><h3>＠ &nbsp; Actividad reciente <span>⋮</span></h3><p>Creaste la tarea “Nueva tarea”</p><p>Actualizaste un proyecto</p></article><article class="widget"><h3>▦ &nbsp; Próximos vencimientos <span>⋮</span></h3><p>Nueva tarea</p><small>05 oct 2026</small></article><article class="widget"><h3>› &nbsp; Navegación rápida <span>⋮</span></h3><p>Crear una tarea &nbsp; ›</p><p>Crear un proyecto &nbsp; ›</p></article></div><div class="widget-gallery reveal"><header><small>PERSONALIZA TU INICIO</small><h3>Galería de widgets</h3><p>Elige y agrega varias copias.</p></header><article><h4>Indicadores</h4><div>5 Mis tareas &nbsp; · &nbsp; 2 Vencen hoy &nbsp; · &nbsp; 0 En curso</div><button class="primary gallery-add">＋ Agregar</button></article><article><h4>Mis tareas</h4><p>Lo pendiente para hoy y los próximos días</p><button class="primary">＋ Agregar</button></article><footer>Listo</footer></div><div class="detail-drawer reveal"><div class="detail-top"><small>DETALLE DE TAREA</small><span>▣ &nbsp; ✎ &nbsp; ♲ &nbsp; ×</span></div><h3>◯ &nbsp; Nueva tarea</h3><dl><dt>Responsable</dt><dd>Sin responsable</dd><dt>Seguidores</dt><dd>Ninguno</dd><dt>Fecha límite</dt><dd>Sin fecha</dd><dt>Proyecto</dt><dd>Sin proyecto</dd><dt>Prioridad</dt><dd>Media</dd></dl><div class="detail-block">Colaboradores asignados (0) <span>Modificar</span></div><h4>SUBTAREAS <span>0 de 0</span></h4><div class="detail-line"></div><div class="detail-entry">＋ &nbsp; Agregar subtarea...</div><h4>COMENTARIOS <span>0</span></h4><p>Aún no hay comentarios.</p><div class="detail-entry">▧ &nbsp; Escribe un comentario...</div></div>`;
scenes[1].querySelector('.copy p').textContent = 'Personaliza tus widgets y abre una tarea para consultar todos sus detalles.';
scenes[2].querySelector('.tour-editor-fields label:first-child .field').innerHTML = '<span class="task-name"></span><span class="typing-caret">|</span>';
scenes[2].querySelector('.tour-board').innerHTML = `<section class="board-source"><header>SIN SECCIÓN <span>3</span></header><article><strong>Revisar propuesta</strong><small>Media · 07 oct</small></article><article><strong>Preparar presentación</strong><small>Alta · 05 oct</small></article><article class="movable-task"><strong>Enviar propuesta</strong><small>Alta · 06 oct</small></article><button>+ Agregar tarea</button></section><section class="board-target reveal"><header>REVISIÓN <span class="board-count">0</span></header><div class="board-destination"></div><button>+ Agregar tarea</button></section><button class="board-add-section">+ Nueva sección</button><div class="board-section-form reveal"><div class="field">Revisión</div><button class="primary board-create-section">Crear sección</button></div><article class="drag-ghost"><strong>Enviar propuesta</strong><small>Alta · 06 oct</small></article>`;
scenes[2].querySelector('.copy p').textContent = 'Escribe el nombre, crea una sección y arrastra la tarea a otra columna.';
scenes[3].querySelector('.app main').innerHTML = `<header class="with-button"><div><small>PROYECTOS</small><h2>Proyectos</h2><small>Supervisa los proyectos activos de cada departamento.</small></div><button class="primary action project-add">＋ Crear proyecto</button></header><div class="project-empty">No hay proyectos<p>Prueba otro nombre o crea un proyecto.</p></div><div class="project-card reveal"><h3><i></i> Campaña Aurora <span>Activo · Media</span></h3><p>30 sep 2026 — Sin fecha final</p><div class="progress"><div style="width:0%"></div></div><small>0 de 0 tareas completadas</small><b>0%</b></div><div class="project-editor reveal"><div class="project-fields"><label><b>1</b> Nombre del proyecto<div class="field project-name">Campaña Aurora</div></label><label><b>2</b> Descripción<div class="field tall">Campaña de lanzamiento</div></label><h4>Departamento responsable</h4><div class="editor-cols"><label>Departamento<div class="field">Marketing ⌄</div></label><label>Responsable<div class="field">Sin responsable ⌄</div></label></div><label><b>3</b> Color del proyecto<div class="color-dots">● &nbsp; ● &nbsp; ● &nbsp; ● &nbsp; ● &nbsp; ●</div></label><label>Imagen del proyecto<div class="field">🔴 &nbsp; Subir foto</div></label><label><b>4</b> Información existente del proyecto</label><div class="editor-cols"><label>Fecha de inicio<div class="field">30 sep 2026</div></label><label>Fecha de fin<div class="field">Seleccionar fecha</div></label></div><label>Estado inicial<div class="field">Activo ⌄</div></label><label>Prioridad<div class="field">Media ⌄</div></label><label><b>5</b> Personas relacionadas al proyecto</label></div><footer><button>Cancelar</button><button class="primary project-save">Crear proyecto</button></footer></div>`;
scenes[3].querySelector('.copy p').textContent = 'Crea un proyecto en Marketing, define sus datos y consulta su progreso.';
scenes[3].querySelector('.copy h1').textContent = 'Cada proyecto, en su lugar.';
// These are deliberate modal/drawer layers; annotate the actual text nodes for layout QA.
for (const [index, selector] of [[0,'.login-options'],[0,'.role-menu'],[1,'main header'],[1,'.home-grid'],[1,'.widget-gallery'],[1,'.detail-drawer'],[3,'main header'],[3,'.project-empty'],[3,'.project-editor'],[5,'.calendar-tools'],[5,'.event-editor']]) {
  scenes[index].querySelector(selector)?.querySelectorAll('*').forEach(node => node.setAttribute('data-layout-allow-overlap',''));
}
