# Generated by Django 5.2.17 on 2026-10-04 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_workspace', '0002_publishedview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_subject', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=200)),
                ('working_id', models.CharField(max_length=200)),
                ('checksum', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'google_subject', 'source_id'), name='workspace_office_original')],
            },
        ),
    ]
