# Generated by Django 5.2.17 on 2026-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_workspace', '0003_officeworkspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255)),
                ('client_secret_encrypted', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='googleconnection',
            name='client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='googleconnection',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=80),
        ),
    ]
