# Generated by Django 5.2.17 on 2026-10-08 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_workspace', '0005_bind_existing_oauth_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorageRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('google_email', models.EmailField(max_length=254)),
                ('client_id', models.CharField(max_length=255)),
                ('folder_id', models.CharField(max_length=200)),
                ('folder_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageStorageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=700)),
                ('drive_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boldApp_workspace.imagestorageroot')),
            ],
        ),
        migrations.CreateModel(
            name='StoredImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drive_id', models.CharField(max_length=200)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boldApp_workspace.imagestorageroot')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_kind', models.CharField(max_length=30)),
                ('resource_id', models.UUIDField()),
                ('field', models.CharField(max_length=40)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='boldApp_workspace.storedimage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='imagestorageroot',
            constraint=models.UniqueConstraint(fields=('user', 'subject', 'client_id', 'folder_id'), name='image_storage_destination'),
        ),
        migrations.AddConstraint(
            model_name='imagestorageroot',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='one_active_image_destination'),
        ),
        migrations.AddConstraint(
            model_name='imagestoragefolder',
            constraint=models.UniqueConstraint(fields=('root', 'key'), name='image_storage_folder_key'),
        ),
        migrations.AddConstraint(
            model_name='imagebinding',
            constraint=models.UniqueConstraint(fields=('image', 'resource_kind', 'resource_id', 'field'), name='image_resource_binding'),
        ),
    ]
