# Generated by Django 5.2.17 on 2026-10-08 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_workspace', '0006_imagestorageroot_imagestoragefolder_storedimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_subject', models.CharField(blank=True, max_length=255)),
                ('assignment_id', models.UUIDField(null=True)),
                ('kind', models.CharField(max_length=30)),
                ('external_id', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'google_subject', 'kind', 'external_id'), name='image_document_resource')],
            },
        ),
    ]
