# Generated by Django 5.2.17 on 2026-09-08 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=140)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('level', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_roles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('resource', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=180, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to='boldApp_core.employee')),
            ],
            options={
                'db_table': 'user_accounts',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('unit_type', models.CharField(max_length=30)),
                ('sensitivity_level', models.CharField(max_length=20)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_units', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'organizational_units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrantAuthority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_sensitivity_level', models.CharField(max_length=20)),
                ('can_grant_access', models.BooleanField(default=False)),
                ('can_revoke_access', models.BooleanField(default=False)),
                ('can_delegate_authority', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grant_authorities', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'grant_authorities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(max_length=30)),
                ('effect', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='boldApp_core.jobrole')),
                ('target_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_permission_scopes', to='boldApp_core.organizationalunit')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='boldApp_core.permission')),
            ],
            options={
                'db_table': 'job_role_permissions',
            },
        ),
        migrations.CreateModel(
            name='GrantAuthorityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_permissions', to='boldApp_core.grantauthority')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_authority_links', to='boldApp_core.permission')),
            ],
            options={
                'db_table': 'grant_authority_permissions',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='boldApp_core.jobrole')),
                ('reports_to_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='boldApp_core.position')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['unit', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='PositionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_assignments', to='boldApp_core.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='boldApp_core.position')),
            ],
            options={
                'db_table': 'position_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('decision', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_audit_logs', to='boldApp_core.employee')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='boldApp_core.permission')),
                ('target_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_audit_logs', to='boldApp_core.organizationalunit')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_logs', to='boldApp_core.positionassignment')),
            ],
            options={
                'db_table': 'permission_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_authorities', to='boldApp_core.positionassignment'),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='granted_by_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_authorities_issued', to='boldApp_core.positionassignment'),
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('target_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='boldApp_core.organizationalunit')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='boldApp_core.permission')),
                ('granted_by_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants_issued', to='boldApp_core.positionassignment')),
                ('grantee_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants_received', to='boldApp_core.positionassignment')),
                ('revoked_by_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants_revoked', to='boldApp_core.positionassignment')),
            ],
            options={
                'db_table': 'access_grants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationalunit',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_unit')), _negated=True), name='organizational_unit_cannot_be_its_own_parent'),
        ),
        migrations.AddConstraint(
            model_name='jobrolepermission',
            constraint=models.UniqueConstraint(fields=('job_role', 'permission'), name='unique_job_role_permission'),
        ),
        migrations.AddConstraint(
            model_name='grantauthoritypermission',
            constraint=models.UniqueConstraint(fields=('grant_authority', 'permission'), name='unique_grant_authority_permission'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('reports_to_position')), _negated=True), name='position_cannot_report_to_itself'),
        ),
        migrations.AddIndex(
            model_name='positionassignment',
            index=models.Index(fields=['employee', 'is_active'], name='idx_posasg_employee_active'),
        ),
        migrations.AddConstraint(
            model_name='positionassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('released_at__isnull', True)), fields=('position',), name='unique_active_assignment_per_position'),
        ),
        migrations.AddConstraint(
            model_name='positionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', False), ('released_at__isnull', True), _connector='OR'), name='active_assignment_has_no_release_date'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['employee', 'created_at'], name='idx_permauditlog_emp_created'),
        ),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['grantee_assignment', 'status'], name='idx_accessgrant_grantee_status'),
        ),
    ]
