# Generated by Django 5.2.17 on 2026-09-16 18:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('boldApp_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='credentials_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_user_email_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='useraccount',
            constraint=models.CheckConstraint(condition=models.Q(('email__endswith', '@bold.gt')), name='user_email_must_be_bold_gt'),
        ),
    ]
