# Generated by Django 5.2.17 on 2026-09-18 22:05

import datetime
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


PERMISSION_CATALOG = [
    ("tasks.task.read", "tasks", "task", "read", "low", True, False, "Consultar tareas."),
    ("tasks.task.create", "tasks", "task", "create", "medium", True, False, "Crear tareas."),
    ("tasks.task.update", "tasks", "task", "update", "medium", True, False, "Editar tareas."),
    ("tasks.task.delete", "tasks", "task", "delete", "high", True, False, "Eliminar tareas."),
    ("tasks.task.assign", "tasks", "task", "assign", "high", True, False, "Mover o reasignar tareas."),
    ("tasks.comment.create", "tasks", "comment", "create", "low", True, False, "Comentar en tareas."),
    ("tasks.project.read", "tasks", "project", "read", "low", True, False, "Consultar proyectos."),
    ("tasks.project.manage", "tasks", "project", "manage", "high", True, False, "Administrar proyectos."),
    ("tasks.catalog.read", "tasks", "catalog", "read", "low", True, False, "Consultar estados y etiquetas."),
    ("tasks.webhook.manage", "tasks", "webhook", "manage", "critical", True, True, "Administrar webhooks salientes."),
    ("permissions.module.access", "permissions", "module", "access", "low", True, False, "Abrir el módulo de permisos."),
    ("permissions.policy.read", "permissions", "policy", "read", "medium", False, False, "Consultar políticas de acceso."),
    ("permissions.policy.manage", "permissions", "policy", "manage", "critical", False, True, "Modificar políticas por cargo."),
    ("permissions.audit.read", "permissions", "audit", "read", "high", False, True, "Consultar auditoría de permisos."),
    ("permissions.authority.manage", "permissions", "authority", "manage", "critical", False, True, "Administrar autoridades delegadas."),
    ("permissions.simulate", "permissions", "decision", "simulate", "high", False, True, "Simular decisiones de acceso."),
]


def harden_existing_permission_data(apps, schema_editor):
    Permission = apps.get_model("boldApp_core", "Permission")
    JobRolePermission = apps.get_model("boldApp_core", "JobRolePermission")
    AccessGrant = apps.get_model("boldApp_core", "AccessGrant")
    GrantAuthority = apps.get_model("boldApp_core", "GrantAuthority")
    GrantAuthorityPermission = apps.get_model("boldApp_core", "GrantAuthorityPermission")
    PermissionAuditLog = apps.get_model("boldApp_core", "PermissionAuditLog")

    # Permission.code ya era unico de forma sensible a mayusculas en algunos
    # motores. Antes de agregar la unicidad sobre Lower(code), fusiona
    # variantes equivalentes y reasigna todas las FK del estado historico.
    permission_groups = {}
    for permission in Permission.objects.all().order_by("created_at", "id"):
        normalized_code = (permission.code or "").strip().lower()
        permission_groups.setdefault(normalized_code, []).append(permission)

    for normalized_code, duplicates in permission_groups.items():
        canonical = next(
            (permission for permission in duplicates if permission.code == normalized_code),
            duplicates[0],
        )
        for duplicate in duplicates:
            if duplicate.pk == canonical.pk:
                continue

            JobRolePermission.objects.filter(permission_id=duplicate.pk).update(
                permission_id=canonical.pk
            )
            AccessGrant.objects.filter(permission_id=duplicate.pk).update(
                permission_id=canonical.pk
            )
            PermissionAuditLog.objects.filter(permission_id=duplicate.pk).update(
                permission_id=canonical.pk
            )

            # Esta relacion ya tenia unicidad (authority, permission) en 0001.
            for link in GrantAuthorityPermission.objects.filter(
                permission_id=duplicate.pk
            ).iterator():
                canonical_link_exists = GrantAuthorityPermission.objects.filter(
                    grant_authority_id=link.grant_authority_id,
                    permission_id=canonical.pk,
                ).exclude(pk=link.pk).exists()
                if canonical_link_exists:
                    link.delete()
                else:
                    GrantAuthorityPermission.objects.filter(pk=link.pk).update(
                        permission_id=canonical.pk
                    )

            Permission.objects.filter(pk=duplicate.pk).delete()

        Permission.objects.filter(pk=canonical.pk).update(code=normalized_code)

    for code, module, resource, action, risk, delegable, step_up, description in PERMISSION_CATALOG:
        Permission.objects.update_or_create(
            code=code,
            defaults={
                "module_code": module,
                "resource": resource,
                "action": action,
                "risk_level": risk,
                "is_delegable": delegable,
                "requires_step_up_mfa": step_up,
                "is_active": True,
                "system_managed": True,
                "description": description,
            },
        )
    for permission in Permission.objects.all():
        module = permission.code.split(".", 1)[0].strip().lower() or "core"
        updates = {}
        if permission.module_code != module:
            updates["module_code"] = module
        if updates:
            Permission.objects.filter(pk=permission.pk).update(**updates)

    valid_scopes = {"global", "own_unit", "sub_tree", "specific_unit"}

    # Corrige reglas mal formadas sin ampliar su alcance. Los nombres de cargo
    # no se usan para reconstruir perfiles: son datos empresariales mutables.
    for rule in JobRolePermission.objects.all().iterator():
        scope_type = rule.scope_type
        target_unit_id = rule.target_unit_id
        if scope_type not in valid_scopes:
            scope_type = "specific_unit" if target_unit_id else "own_unit"
        elif scope_type == "global" and target_unit_id:
            scope_type = "specific_unit"
        elif scope_type == "own_unit":
            target_unit_id = None
        elif scope_type in {"specific_unit", "sub_tree"} and not target_unit_id:
            scope_type = "own_unit"
            target_unit_id = None

        JobRolePermission.objects.filter(pk=rule.pk).update(
            scope_type=scope_type,
            target_unit_id=target_unit_id,
            effect=rule.effect if rule.effect in {"allow", "deny"} else "deny",
        )

    # La fusion de codigos puede hacer converger dos reglas. Deny prevalece
    # cuando las filas originales entraban en conflicto.
    role_rules = {}
    for rule in JobRolePermission.objects.all().order_by("created_at", "pk"):
        key = (
            rule.job_role_id,
            rule.permission_id,
            rule.scope_type,
            rule.target_unit_id,
        )
        survivor = role_rules.get(key)
        if survivor is None:
            role_rules[key] = rule
            continue
        if survivor.effect != "deny" and rule.effect == "deny":
            JobRolePermission.objects.filter(pk=survivor.pk).update(effect="deny")
            survivor.effect = "deny"
        JobRolePermission.objects.filter(pk=rule.pk).delete()

    now = django.utils.timezone.now()
    for grant in AccessGrant.objects.select_related("granted_by_assignment__employee").all():
        scope_type = grant.scope_type
        target_unit_id = grant.target_unit_id
        if scope_type not in valid_scopes:
            scope_type = "specific_unit" if target_unit_id else "own_unit"
        elif scope_type == "global" and target_unit_id:
            scope_type = "specific_unit"
        elif scope_type == "own_unit":
            target_unit_id = None
        elif scope_type in {"specific_unit", "sub_tree"} and not target_unit_id:
            scope_type = "own_unit"
            target_unit_id = None

        updates = {
            "scope_type": scope_type,
            "target_unit_id": target_unit_id,
            "effect": grant.effect if grant.effect in {"allow", "deny"} else "deny",
        }
        account = getattr(grant.granted_by_assignment.employee, "user_account", None)
        if account:
            updates["created_by_account_id"] = account.id

        is_revoked = grant.status == "revoked" or grant.revoked_at is not None
        if is_revoked:
            updates["status"] = "revoked"
            if grant.revoked_at is None:
                updates["revoked_at"] = grant.created_at or now
        elif grant.status not in {"active", "expired"}:
            updates["status"] = "expired"
        elif grant.status == "expired" or (
            grant.valid_until is not None and grant.valid_until <= now
        ):
            updates["status"] = "expired"

        if grant.valid_until is not None and grant.valid_until <= grant.valid_from:
            updates["valid_until"] = grant.valid_from + datetime.timedelta(seconds=1)
            if not is_revoked:
                updates["status"] = "expired"
        AccessGrant.objects.filter(pk=grant.pk).update(**updates)

    for authority in GrantAuthority.objects.select_related("granted_by_assignment__employee").all():
        target_unit_id = authority.target_unit_id
        # scope_type no existia antes de esta migracion. El default tecnico
        # sub_tree no debe ampliar una autoridad legacy: una unidad antigua se
        # interpreta como exacta y la ausencia de unidad como unidad propia.
        scope_type = "specific_unit" if target_unit_id else "own_unit"

        updates = {
            "scope_type": scope_type,
            "target_unit_id": target_unit_id,
        }
        account = getattr(authority.granted_by_assignment.employee, "user_account", None)
        if account:
            updates["created_by_account_id"] = account.id

        # Una autoridad heredada sin vencimiento no conserva poder permanente.
        # La fila queda disponible para auditoria, pero inactiva y cerrada.
        if authority.valid_until is None:
            updates["valid_until"] = (
                now
                if now > authority.valid_from
                else authority.valid_from + datetime.timedelta(microseconds=1)
            )
            updates["is_active"] = False
        elif authority.valid_until <= authority.valid_from:
            updates["valid_until"] = authority.valid_from + datetime.timedelta(microseconds=1)
            updates["is_active"] = False
        elif authority.valid_until <= now or authority.revoked_at is not None:
            updates["is_active"] = False
        GrantAuthority.objects.filter(pk=authority.pk).update(**updates)

    for row in PermissionAuditLog.objects.select_related("permission", "employee").all().iterator():
        account = getattr(row.employee, "user_account", None)
        PermissionAuditLog.objects.filter(pk=row.pk).update(
            actor_account_id=account.id if account else None,
            module_code=row.permission.code.split(".", 1)[0],
            resource_type=row.permission.resource,
            decision=row.decision if row.decision in {"allow", "deny"} else "deny",
            reason_code="legacy_decision",
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_core', '0002_useraccount_credentials_version_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobrolepermission',
            name='unique_job_role_permission',
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='created_by_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='effect',
            field=models.CharField(choices=[('allow', 'Permitir'), ('deny', 'Denegar')], default='allow', max_length=10),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='resource_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='resource_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='revoked_by_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('own_unit', 'Unidad propia'), ('sub_tree', 'Subárbol'), ('specific_unit', 'Unidad específica')], default='specific_unit', max_length=30),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='source',
            field=models.CharField(choices=[('temporary', 'Temporal'), ('override', 'Excepción')], default='temporary', max_length=20),
        ),
        migrations.AddField(
            model_name='accessgrant',
            name='source_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_access_grants', to='boldApp_core.grantauthority'),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='created_by_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grant_authorities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='delegation_depth_remaining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='max_grant_duration_seconds',
            field=models.PositiveIntegerField(default=604800),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='parent_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delegated_authorities', to='boldApp_core.grantauthority'),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='reason',
            field=models.TextField(default='Autoridad migrada'),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='revoked_by_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grant_authorities_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('own_unit', 'Unidad propia'), ('sub_tree', 'Subárbol'), ('specific_unit', 'Unidad específica')], default='sub_tree', max_length=30),
        ),
        migrations.AddField(
            model_name='grantauthority',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobrolepermission',
            name='created_by_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_role_permission_rules_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobrolepermission',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrolepermission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_delegable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='module_code',
            field=models.CharField(default='core', max_length=50),
        ),
        migrations.AddField(
            model_name='permission',
            name='requires_step_up_mfa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='permission',
            name='system_managed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='actor_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='correlation_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='matched_rule_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='matched_rule_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='module_code',
            field=models.CharField(default='core', max_length=50),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='policy_version',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='reason_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='resource_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='session_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('revoked', 'Revocado'), ('expired', 'Expirado')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='accessgrant',
            name='target_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='boldApp_core.organizationalunit'),
        ),
        migrations.AlterField(
            model_name='jobrolepermission',
            name='effect',
            field=models.CharField(choices=[('allow', 'Permitir'), ('deny', 'Denegar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobrolepermission',
            name='scope_type',
            field=models.CharField(choices=[('global', 'Global'), ('own_unit', 'Unidad propia'), ('sub_tree', 'Subárbol'), ('specific_unit', 'Unidad específica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='permissionauditlog',
            name='decision',
            field=models.CharField(choices=[('allow', 'Permitir'), ('deny', 'Denegar')], max_length=10),
        ),
        migrations.AlterField(
            model_name='permissionauditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(harden_existing_permission_data, noop_reverse),
        migrations.AddIndex(
            model_name='accessgrant',
            index=models.Index(fields=['permission', 'target_unit', 'status'], name='idx_accessgrant_perm_unit'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('effect__in', ['allow', 'deny'])), name='access_grant_valid_effect'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('scope_type__in', ['global', 'own_unit', 'sub_tree', 'specific_unit'])), name='access_grant_valid_scope'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'revoked', 'expired'])), name='access_grant_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type__in', ['global', 'own_unit']), ('target_unit__isnull', True)), models.Q(('scope_type__in', ['specific_unit', 'sub_tree']), ('target_unit__isnull', False)), _connector='OR'), name='access_grant_scope_target_consistent'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='access_grant_valid_interval'),
        ),
        migrations.AddConstraint(
            model_name='accessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('status', 'revoked')), models.Q(('status', 'revoked'), _negated=True), _connector='OR'), name='access_grant_revocation_timestamp_required'),
        ),
        migrations.AddConstraint(
            model_name='grantauthority',
            constraint=models.CheckConstraint(condition=models.Q(('scope_type__in', ['global', 'own_unit', 'sub_tree', 'specific_unit'])), name='grant_authority_valid_scope'),
        ),
        migrations.AddConstraint(
            model_name='grantauthority',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type__in', ['global', 'own_unit']), ('target_unit__isnull', True)), models.Q(('scope_type__in', ['specific_unit', 'sub_tree']), ('target_unit__isnull', False)), _connector='OR'), name='grant_authority_scope_target_consistent'),
        ),
        migrations.AddConstraint(
            model_name='grantauthority',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='grant_authority_valid_interval'),
        ),
        migrations.AddConstraint(
            model_name='grantauthority',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True)), ('is_active', False), _connector='OR'), name='active_grant_authority_not_revoked'),
        ),
        migrations.AddConstraint(
            model_name='jobrolepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('target_unit__isnull', True)), fields=('job_role', 'permission', 'scope_type'), name='unique_role_permission_scope_without_unit'),
        ),
        migrations.AddConstraint(
            model_name='jobrolepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('target_unit__isnull', False)), fields=('job_role', 'permission', 'scope_type', 'target_unit'), name='unique_role_permission_scope_with_unit'),
        ),
        migrations.AddConstraint(
            model_name='jobrolepermission',
            constraint=models.CheckConstraint(condition=models.Q(('scope_type__in', ['global', 'own_unit', 'sub_tree', 'specific_unit'])), name='job_role_permission_valid_scope'),
        ),
        migrations.AddConstraint(
            model_name='jobrolepermission',
            constraint=models.CheckConstraint(condition=models.Q(('effect__in', ['allow', 'deny'])), name='job_role_permission_valid_effect'),
        ),
        migrations.AddConstraint(
            model_name='jobrolepermission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope_type__in', ['global', 'own_unit']), ('target_unit__isnull', True)), models.Q(('scope_type__in', ['specific_unit', 'sub_tree']), ('target_unit__isnull', False)), _connector='OR'), name='job_role_permission_scope_target_consistent'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_permission_code_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.CheckConstraint(condition=models.Q(('risk_level__in', ['low', 'medium', 'high', 'critical'])), name='permission_valid_risk_level'),
        ),
    ]
