# Generated by Django 5.2.17 on 2026-09-29 12:30

from django.db import migrations, models


def mark_existing_direction_unit(apps, schema_editor):
    OrganizationalUnit = apps.get_model("boldApp_core", "OrganizationalUnit")
    PositionAssignment = apps.get_model("boldApp_core", "PositionAssignment")
    assignment = (
        PositionAssignment.objects.filter(
            is_active=True,
            released_at__isnull=True,
            employee__user_account__is_superuser=True,
        )
        .select_related("position__unit")
        .order_by("assigned_at")
        .first()
    )
    unit = assignment.position.unit if assignment else None
    if unit is None:
        unit = OrganizationalUnit.objects.filter(name__iexact="Dirección").first()
    if unit is None:
        unit = OrganizationalUnit.objects.filter(name__iexact="Direccion").first()
    if unit is not None:
        OrganizationalUnit.objects.filter(pk=unit.pk).update(is_control_plane=True)


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_core', '0007_useraccount_administration_dashboard_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalunit',
            name='is_control_plane',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_direction_unit, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='organizationalunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_control_plane', True)), fields=('is_control_plane',), name='unique_control_plane_unit'),
        ),
    ]
