# Generated by Django 5.2.17 on 2026-10-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_core', '0010_add_dynamic_role_permission_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
