# Generated by Django 5.2.17 on 2026-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_core', '0011_useraccount_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='banner_color',
            field=models.CharField(default='#ef1f2d', max_length=7),
        ),
    ]
