# Generated by Django 5.2.17 on 2026-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_core', '0012_useraccount_banner_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
