# Generated by Django 5.2.17 on 2026-10-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_core', '0011_jobrole_control_plane_modules'),
        ('boldApp_core', '0014_user_shortcut_settings'),
    ]

    operations = [
    ]
