# Generated by Django 5.2.17 on 2026-09-17 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boldApp_core', '0002_useraccount_credentials_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('actor_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_actions', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrative_actions_received', to=settings.AUTH_USER_MODEL)),
                ('target_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrative_actions', to='boldApp_core.employee')),
            ],
            options={
                'db_table': 'administrative_actions',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='OffboardingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Lista'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('failed', 'Fallida')], default='draft', max_length=20)),
                ('reason', models.TextField()),
                ('effective_at', models.DateTimeField()),
                ('responsibility_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('administrative_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offboarding_case', to='boldApp_administrativo.administrativeaction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offboarding_cases', to='boldApp_core.employee')),
                ('initiated_by_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offboarding_cases_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offboarding_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponsibilityTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_module', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('failed', 'Fallida'), ('skipped', 'Omitida')], default='pending', max_length=20)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('offboarding_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='boldApp_administrativo.offboardingcase')),
                ('source_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_transfers_from', to='boldApp_core.positionassignment')),
                ('target_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrative_transfers_to', to='boldApp_core.positionassignment')),
            ],
            options={
                'db_table': 'responsibility_transfers',
                'ordering': ['source_module', 'resource_type', 'resource_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_code', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('outcome', models.CharField(default='success', max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_events', to=settings.AUTH_USER_MODEL)),
                ('administrative_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='boldApp_administrativo.administrativeaction')),
                ('organizational_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_events', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'system_audit_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='administrativeaction',
            index=models.Index(fields=['action_type', 'requested_at'], name='idx_admin_action_type_time'),
        ),
        migrations.AddIndex(
            model_name='administrativeaction',
            index=models.Index(fields=['target_employee', 'requested_at'], name='idx_admin_action_employee'),
        ),
        migrations.AddIndex(
            model_name='offboardingcase',
            index=models.Index(fields=['employee', 'status'], name='idx_offboard_employee_status'),
        ),
        migrations.AddConstraint(
            model_name='responsibilitytransfer',
            constraint=models.UniqueConstraint(fields=('offboarding_case', 'source_module', 'resource_type', 'resource_id'), name='unique_offboarding_resource_transfer'),
        ),
        migrations.AddIndex(
            model_name='systemauditevent',
            index=models.Index(fields=['module_code', 'occurred_at'], name='idx_sysaudit_module_time'),
        ),
        migrations.AddIndex(
            model_name='systemauditevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='idx_sysaudit_event_time'),
        ),
        migrations.AddIndex(
            model_name='systemauditevent',
            index=models.Index(fields=['actor_account', 'occurred_at'], name='idx_sysaudit_actor_time'),
        ),
    ]
