# Generated by Django 5.2.17 on 2026-09-24 21:46

import uuid
from django.db import migrations, models


def seed_options(apps, schema_editor):
    Unit = apps.get_model("boldApp_core", "OrganizationalUnit")
    Option = apps.get_model("boldApp_administrativo", "OrganizationCatalogOption")
    for value in set(Unit.objects.values_list("unit_type", flat=True)) | {"department"}:
        Option.objects.get_or_create(kind="unit_type", value=value)
    for value in set(Unit.objects.values_list("sensitivity_level", flat=True)) | {"normal", "high", "critical"}:
        Option.objects.get_or_create(kind="sensitivity", value=value)


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_administrativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCatalogOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('unit_type', 'Tipo de unidad'), ('sensitivity', 'Sensibilidad')], max_length=20)),
                ('value', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'organization_catalog_options',
                'ordering': ['kind', 'value'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'value'), name='unique_organization_catalog_option')],
            },
        ),
        migrations.RunPython(seed_options, migrations.RunPython.noop),
    ]
