# Generated by Django 5.2.17 on 2026-09-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_administrativo', '0002_organizationcatalogoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationcatalogoption',
            name='kind',
            field=models.CharField(choices=[('unit_type', 'Tipo de unidad'), ('sensitivity', 'Sensibilidad'), ('role_level', 'Nivel de cargo')], max_length=20),
        ),
    ]
