# Generated by Django 5.2.17 on 2026-10-05 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_workspace', '0004_googleoauthconfiguration_googleconnection_client_id_and_more'),
        ('calendario', '0002_calendardraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardraft',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boldApp_workspace.googleconnection'),
        ),
        migrations.AddField(
            model_name='calendardraft',
            name='google_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
