# Generated by Django 5.2.17 on 2026-09-16 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('client_type', models.CharField(choices=[('web', 'Web'), ('pwa', 'PWA'), ('android', 'Android')], default='web', max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('user_agent', models.TextField(blank=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('idle_expires_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_verified_at', models.DateTimeField(blank=True, null=True)),
                ('auth_strength', models.CharField(default='password', max_length=30)),
                ('credentials_version', models.PositiveIntegerField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=80)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_sessions', to='boldApp_autenticacion.authsession')),
                ('revoked_by_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_auth_sessions', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_sessions',
            },
        ),
        migrations.CreateModel(
            name='AuthRecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64)),
                ('batch_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
                ('used_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_recovery_codes', to='boldApp_autenticacion.authsession')),
            ],
            options={
                'db_table': 'auth_recovery_codes',
            },
        ),
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=60)),
                ('success', models.BooleanField(default=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('email_fingerprint', models.CharField(blank=True, max_length=64)),
                ('failure_reason_code', models.CharField(blank=True, max_length=60)),
                ('target_type', models.CharField(blank=True, max_length=60)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('actor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='boldApp_autenticacion.authsession')),
            ],
            options={
                'db_table': 'auth_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('account_invitation', 'Invitación'), ('password_reset', 'Restablecer contraseña'), ('email_verification', 'Verificar correo'), ('email_change', 'Cambiar correo')], max_length=30)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('target_email_normalized', models.EmailField(blank=True, max_length=180, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_challenges',
                'indexes': [models.Index(fields=['user_account', 'purpose', 'expires_at'], name='idx_auth_challenge_lookup')],
            },
        ),
        migrations.CreateModel(
            name='AuthMFAMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('totp', 'TOTP'), ('webauthn', 'WebAuthn')], max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('secret_encrypted', models.TextField(blank=True)),
                ('credential_id', models.BinaryField(blank=True, null=True)),
                ('public_key', models.BinaryField(blank=True, null=True)),
                ('sign_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_by_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disabled_mfa_methods', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_mfa_methods',
                'constraints': [models.UniqueConstraint(fields=('user_account', 'credential_id'), name='unique_user_webauthn_credential')],
            },
        ),
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(fields=['user_account', 'revoked_at', 'expires_at'], name='idx_auth_session_active'),
        ),
        migrations.AddConstraint(
            model_name='authrecoverycode',
            constraint=models.UniqueConstraint(fields=('user_account', 'code_hash'), name='unique_user_recovery_code'),
        ),
        migrations.AddIndex(
            model_name='authevent',
            index=models.Index(fields=['user_account', 'occurred_at'], name='idx_auth_event_user_time'),
        ),
        migrations.AddIndex(
            model_name='authevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='idx_auth_event_type_time'),
        ),
    ]
