# Generated by Django 5.2.17 on 2026-09-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmfamethod',
            name='last_totp_counter',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
