# Generated by Django 5.2.17 on 2026-09-02 11:39

import boldApp.models.webhooks
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boldApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_url", models.URLField()),
                (
                    "secret",
                    models.CharField(
                        default=boldApp.models.webhooks.generate_webhook_secret,
                        editable=False,
                        max_length=64,
                    ),
                ),
                (
                    "event_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de event_type a los que esta suscrito. Vacio = todos los eventos.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="boldApp.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_endpoints",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=40)),
                (
                    "payload",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "response_status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True, null=True)),
                ("succeeded", models.BooleanField(default=False)),
                ("attempt_number", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="boldApp.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "created_at"],
                        name="idx_webhookdel_ep_created",
                    )
                ],
            },
        ),
    ]
