import { http } from "../core/http_client.js";

export const adminApi = {
    dashboard: () => http.request("/api/v2/administration/dashboard/"),
    employees: params => http.list("administration/employees", params),
    employee: id => http.request(`/api/v2/administration/employees/${id}/`),
    createEmployee: body => http.request("/api/v2/administration/employees/", { method: "POST", body }),
    updateEmployee: (id, body) => http.request(`/api/v2/administration/employees/${id}/`, { method: "PATCH", body }),
    resendInvitation: id => http.request(`/api/v2/administration/employees/${id}/resend-invitation/`, { method: "POST", body: {} }),
    assignPosition: (id, position, reason) => http.request(`/api/v2/administration/employees/${id}/assign-position/`, { method: "POST", body: { position, reason } }),
    sessions: id => http.request(`/api/v2/administration/employees/${id}/sessions/`),
    revokeSessions: (id, reason) => http.request(`/api/v2/administration/employees/${id}/revoke-sessions/`, { method: "POST", body: { reason } }),
    resetMfa: (id, reason) => http.request(`/api/v2/administration/employees/${id}/reset-mfa/`, { method: "POST", body: { reason } }),
    sendPasswordReset: (id, reason) => http.request(`/api/v2/administration/employees/${id}/send-password-reset/`, { method: "POST", body: { reason } }),
    deactivateAccount: (id, reason) => http.request(`/api/v2/administration/employees/${id}/deactivate-account/`, { method: "POST", body: { reason } }),
    reactivateAccount: (id, reason) => http.request(`/api/v2/administration/employees/${id}/reactivate-account/`, { method: "POST", body: { reason } }),
    offboardingPreview: id => http.request(`/api/v2/administration/employees/${id}/offboarding-preview/`),
    offboard: (id, body) => http.request(`/api/v2/administration/employees/${id}/offboard/`, { method: "POST", body }),
    auditEvents: params => http.list("administration/audit-events", params),
    organization: () => http.request("/api/v2/administration/organization/"),
    createUnit: body => http.request("/api/v2/administration/units/", { method: "POST", body }),
    updateUnit: (id, body) => http.request(`/api/v2/administration/units/${id}/`, { method: "PATCH", body }),
    createRole: body => http.request("/api/v2/administration/roles/", { method: "POST", body }),
    updateRole: (id, body) => http.request(`/api/v2/administration/roles/${id}/`, { method: "PATCH", body }),
    createPosition: body => http.request("/api/v2/administration/positions/", { method: "POST", body }),
    updatePosition: (id, body) => http.request(`/api/v2/administration/positions/${id}/`, { method: "PATCH", body }),
    offboardingCases: () => http.list("administration/offboarding-cases"),
};
