# Generated by Django 5.2.17 on 2026-10-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_sugerencias', '0002_suggestion_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='environment',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='title',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
