# Generated by Django 5.2.17 on 2026-09-18 22:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_policy_state(apps, schema_editor):
    PermissionPolicyState = apps.get_model("boldApp_permisos", "PermissionPolicyState")
    PermissionPolicyState.objects.get_or_create(key="global", defaults={"revision": 1})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boldApp_core', '0003_remove_jobrolepermission_unique_job_role_permission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionPolicyState',
            fields=[
                ('key', models.CharField(default='global', editable=False, max_length=30, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permission_policy_state',
            },
        ),
        migrations.CreateModel(
            name='PermissionPolicyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('outcome', models.CharField(choices=[('success', 'Éxito'), ('denied', 'Denegado'), ('failure', 'Error')], default='success', max_length=20)),
                ('target_type', models.CharField(max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField()),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('mfa_verified', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_policy_events', to=settings.AUTH_USER_MODEL)),
                ('actor_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_policy_events', to='boldApp_core.positionassignment')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_events', to='boldApp_core.permission')),
                ('target_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_policy_events', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'permission_policy_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='idx_perm_event_type_time'), models.Index(fields=['actor_account', 'occurred_at'], name='idx_perm_event_actor_time'), models.Index(fields=['revision'], name='idx_perm_event_revision')],
            },
        ),
        migrations.RunPython(create_policy_state, migrations.RunPython.noop),
    ]
