# Generated by Django 5.2.17 on 2026-09-08 22:16

import boldApp.tareas.models.webhooks
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boldApp_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(max_length=30)),
                ('sensitivity_level', models.CharField(blank=True, max_length=20, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_task_projects', to='boldApp_core.positionassignment')),
                ('owner_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_task_projects', to='boldApp_core.positionassignment')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_projects', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_role', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('added_by_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_project_members_added', to='boldApp_core.positionassignment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_project_memberships', to='boldApp_core.positionassignment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='boldApp_tareas.project')),
            ],
            options={
                'db_table': 'project_members',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('position', models.DecimalField(decimal_places=10, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='boldApp_tareas.project')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_tags', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to='boldApp_core.positionassignment')),
                ('created_by_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to='boldApp_core.positionassignment')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='boldApp_tareas.task')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notifications', to='boldApp_core.positionassignment')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='boldApp_tareas.task')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_comments', to='boldApp_core.positionassignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boldApp_tareas.task')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.TextField()),
                ('mime_type', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_attachments_uploaded', to='boldApp_core.positionassignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='boldApp_tareas.task')),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=60)),
                ('field_name', models.CharField(blank=True, max_length=80, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_activity_logs', to='boldApp_core.positionassignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='boldApp_tareas.task')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_dependencies_created', to='boldApp_core.positionassignment')),
                ('depends_on_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks', to='boldApp_tareas.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_dependencies', to='boldApp_tareas.task')),
            ],
            options={
                'db_table': 'task_dependencies',
            },
        ),
        migrations.CreateModel(
            name='TaskFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('notification_level', models.CharField(max_length=20)),
                ('added_by_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_followers_added', to='boldApp_core.positionassignment')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_tasks', to='boldApp_core.positionassignment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='boldApp_tareas.task')),
            ],
            options={
                'db_table': 'task_followers',
            },
        ),
        migrations.CreateModel(
            name='TaskProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.DecimalField(decimal_places=10, max_digits=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_projects_added', to='boldApp_core.positionassignment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_projects', to='boldApp_tareas.project')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_projects', to='boldApp_tareas.section')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_projects', to='boldApp_tareas.task')),
            ],
            options={
                'db_table': 'task_projects',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=30)),
                ('color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('position', models.SmallIntegerField()),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_statuses', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'task_statuses',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='boldApp_tareas.taskstatus'),
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_tags_added', to='boldApp_core.positionassignment')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='boldApp_tareas.tag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='boldApp_tareas.task')),
            ],
            options={
                'db_table': 'task_tags',
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.URLField()),
                ('secret', models.CharField(default=boldApp.tareas.models.webhooks.generate_webhook_secret, editable=False, max_length=64)),
                ('event_types', models.JSONField(blank=True, default=list, help_text='Lista de event_type a los que esta suscrito. Vacio = todos los eventos.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_endpoints', to='boldApp_core.organizationalunit')),
            ],
            options={
                'db_table': 'webhook_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=40)),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('response_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='boldApp_tareas.webhookendpoint')),
            ],
            options={
                'db_table': 'webhook_deliveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_project_name_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'assignment'), name='unique_project_assignment'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_section_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_tag_name_per_unit'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_assignment', 'is_read'], name='idx_notifications_asg_read'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['task', 'created_at'], name='idx_comments_task_created'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on_task'), name='unique_task_dependency'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('task', models.F('depends_on_task')), _negated=True), name='task_cannot_depend_on_itself'),
        ),
        migrations.AddConstraint(
            model_name='taskfollower',
            constraint=models.UniqueConstraint(fields=('task', 'assignment'), name='unique_task_follower'),
        ),
        migrations.AddIndex(
            model_name='taskproject',
            index=models.Index(fields=['project', 'section', 'position'], name='idx_taskprojects_proj_sec_pos'),
        ),
        migrations.AddConstraint(
            model_name='taskproject',
            constraint=models.UniqueConstraint(fields=('task', 'project'), name='unique_task_project'),
        ),
        migrations.AddConstraint(
            model_name='taskstatus',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_task_status_name_per_unit'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee_assignment', 'due_date'], name='idx_tasks_assignment_due'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['unit', 'status'], name='idx_tasks_unit_status'),
        ),
        migrations.AddConstraint(
            model_name='tasktag',
            constraint=models.UniqueConstraint(fields=('task', 'tag'), name='unique_task_tag'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', 'created_at'], name='idx_webhookdel_ep_created'),
        ),
    ]
