# Generated by Django 5.2.17 on 2026-10-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_core', '0017_account_connector_delegation'),
        ('boldApp_tareas', '0009_project_unsectioned_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='voice_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_next_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='boldApp_tareas.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='voice_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('recurrence_source', 'recurrence_date'), name='unique_task_occurrence'),
        ),
    ]
