# Generated by Django 5.2.17 on 2026-10-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boldApp_tareas', '0010_comment_voice_notes_task_recurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image_project_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='image_section',
            field=models.CharField(choices=[('comments', 'Comentarios'), ('timeline', 'Cronograma')], default='comments', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='image_origin_project_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='image_origin_set',
            field=models.BooleanField(default=False),
        ),
    ]
